### ISSUE TITLE
Weird index issue

### ISSUE THREAD

**Issue by dgershman** [radiusmethod/kxd#54]
When I select a profile, it seems to pick the one before.  See here: https://asciinema.org/a/fOH15FOSGG4GzclyGtHRCu04V

**Comment by pjaudiomv** [comment]
Do you know if this Happened in 0.1.1

**Comment by dgershman** [comment]
I don’t think so.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pjaudiomv** [comment]
This should be resolved in 0.1.3 if you upgrade. You can find upgrade instructions here https://github.com/radiusmethod/kxd?tab=readme-ov-file#upgrading

**Comment by dgershman** [comment]
In da seas

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
