### ISSUE TITLE
Integrate context switching

### ISSUE THREAD

**Issue by dgershman** [radiusmethod/kxd#9]
kxd is cool, but it would be cooler if you could also change contexts within each file.

**Comment by pjaudiomv** [comment]
looks like `k8s.io/client-go/tools/clientcmd` would be the way to go

https://pkg.go.dev/k8s.io/client-go/tools/clientcmd

**Comment by pjaudiomv** [comment]
I think an easy MVP would be to just allow for switching contexts for current set `KUBECONFIG` so you could `kxd` choose config then say `kxd -c` and pick context idk

**Comment by pjaudiomv** [comment]
that or if no `KUBECONFIG` set send them through the config picker loop, or default to `~/.kube/config`

**Comment by dgershman** [comment]
Yes I think that makes sense.  You should only be able to switch contexts for the current one.  And the default should be ~/.kube/config.

**Comment by pjaudiomv** [comment]
completed by https://github.com/radiusmethod/kxd/pull/12
